services:
  postgres:
    image: "postgres:16"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: real-estate-monitoring
    restart: unless-stopped

volumes:
  db_data: