CREATE TABLE funcionarios
(
    id                        UUID PRIMARY KEY,
    nome                      VARCHAR(255),
    sexo                      VARCHAR(255),
    cpf                       VARCHAR(11) UNIQUE NOT NULL,
    rg                        VARCHAR(15) NOT NULL,
    uf                        VARCHAR(255),
    telefone_1                VARCHAR(255),
    telefone_2                VARCHAR(255),
    email                     VARCHAR(255),
    data_nascimento           DATE,
    quantidade_filhos         INTEGER,
    nome_mae                  VARCHAR(255),
    nome_pai                  VARCHAR(255),
    is_terceiro               BOOLEAN,
    ativo                     BOOLEAN,
    regime_de_trabalho        VARCHAR(255),
    observacoes_remuneracao   VARCHAR(255),
    funcao                    VARCHAR(255),
    nivel                     VARCHAR(255),
    data_admissao             DATE,
    data_demissao             DATE,
    perfil                    VARCHAR(255),
    conta_bancaria            VARCHAR(255),
    empresa_referencia_1      VARCHAR(255),
    contato_referencia_1      VARCHAR(255),
    telefone_referencia_1     VARCHAR(255),
    empresa_referencia_2      VARCHAR(255),
    contato_referencia_2      VARCHAR(255),
    telefone_referencia_2     VARCHAR(255)
);