import type { IClienteItem } from 'src/types/cliente';


export const _clienteList: IClienteItem[] = [
  {
    id: '1',
    tipo: 'juridica',
    nome: 'ARA IMÓVEIS',
    razaoSocial: 'ARA Imóveis Ltda',
    cnpj: '12.345.678/0001-90',
    setor: 'Imobiliária',
    contato: 'João Silva',
    telefone: '(43) 99911-8988',
    email: 'joao@araimoveis.com.br',
    fonte: 'Site',
    status: 'ativo',
    createdAt: new Date(),
  },
  {
    id: '2',
    tipo: 'juridica',
    nome: 'CONSTRUTORA ALMEIDA',
    razaoSocial: 'Construtora Almeida S.A.',
    cnpj: '98.765.432/0001-10',
    setor: 'Construção',
    contato: 'Maria Almeida',
    telefone: '(43) 99822-7766',
    email: 'maria@construtoralmeida.com.br',
    fonte: 'Indicação',
    status: 'ativo',
    createdAt: new Date(),
  },
  {
    id: '3',
    tipo: 'juridica',
    nome: 'CARLOS RIBEIRO CORRETORES',
    razaoSocial: 'Carlos Ribeiro Corretores Ltda',
    cnpj: '11.222.333/0001-44',
    setor: 'Corretagem',
    contato: 'Carlos Ribeiro',
    telefone: '(43) 99733-5544',
    email: 'carlos@crribeiro.com.br',
    fonte: 'Google Ads',
    status: 'inativo',
    createdAt: new Date(),
  },
  {
    id: '4',
    tipo: 'juridica',
    nome: 'TORRES & ASSOCIADOS',
    razaoSocial: 'Torres & Associados Imobiliária Ltda',
    cnpj: '55.666.777/0001-88',
    setor: 'Imobiliária',
    contato: 'Ana Torres',
    telefone: '(43) 99644-3322',
    email: 'ana@torresassociados.com.br',
    fonte: 'Facebook',
    status: 'ativo',
    createdAt: new Date(),
  },
  {
    id: '5',
    tipo: 'juridica',
    nome: 'BETA INCORPORADORA',
    razaoSocial: 'Beta Incorporadora e Construções Ltda',
    cnpj: '77.888.999/0001-22',
    setor: 'Incorporação',
    contato: 'Pedro Santos',
    telefone: '(43) 99555-1100',
    email: 'pedro@betaincorporadora.com.br',
    fonte: 'LinkedIn',
    status: 'inativo',
    createdAt: new Date(),
  },
  {
    id: '6',
    tipo: 'fisica',
    nome: 'João da Silva Santos',
    cpf: '123.456.789-00',
    rg: '12.345.678-9',
    setor: 'Corretor Autônomo',
    contato: 'João Santos',
    telefone: '(43) 99888-7777',
    email: 'joao.santos@email.com',
    fonte: 'Indicação',
    status: 'ativo',
    createdAt: new Date(),
  },
  {
    id: '7',
    tipo: 'fisica',
    nome: 'Maria Fernanda Oliveira',
    cpf: '987.654.321-00',
    rg: '98.765.432-1',
    setor: 'Investidora',
    contato: 'Maria Oliveira',
    telefone: '(43) 99777-6666',
    email: 'maria.oliveira@gmail.com',
    fonte: 'Google Ads',
    status: 'ativo',
    createdAt: new Date(),
  },
];

export const CLIENTE_STATUS_OPTIONS = [
{ value: 'ativo', label: 'Ativo' },
{ value: 'inativo', label: 'Inativo' },
];